
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-username: cm9vdA==
  mysql-password: RnEzczloWnVVeA==

  # Fq3s9hZuUx - decoded value of mysql pwd

  # root - decoded value of mysql username




